name: study_sphere
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  syncfusion_flutter_charts: ^19.1.66

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite: ^2.0.3+1
  encrypt: ^5.0.0
  bcrypt: ^1.1.3
#  fl_chart: ^0.40.0
  syncfusion_flutter_charts: ^20.1.55



uses-material-design: true

flutter:
  assets:
    - Assets/Images/Back_button.png
    - Assets/Images/signup_combine.png
    - Assets/Images/login_combine.png
    - Assets/Images/background_login.png
    - Assets/Images/4.png
    - Assets/Images/Avatar.png
    - Assets/Images/Search_icon.png
    - Assets/Images/Notification_icon.png
    - Assets/Images/JavaFramework.png
    - Assets/Images/Flutter.png
    - Assets/Images/ADBMS.png
    - Assets/Images/Emotional_int.png
    - Assets/Images/Webservices.png
    - Assets/Images/Game_pro.png
    - Assets/Images/Home_quicknav.png
    - Assets/Images/Notes_quicknav.png
    - Assets/Images/video_lect_quicknav.png
    - Assets/Images/community_quicknav.png
    - Assets/Images/Test_sec_icon.png
    - Assets/Images/question_paper_icon.png
    - Assets/Images/16dig_char_icon.png
    - Assets/Images/google_logo.png
    - Assets/Images/or_logo.png
    - Assets/Images/character_logo.png
    - Assets/Images/signin_combine.png
    - Assets/Images/Announcement_icon.png
    - Assets/Images/Continue_watching_icon.png
    - Assets/Images/5.png
    - Assets/Images/Quiz_next.png
    - Assets/Images/Quiz_exit.png
    - Assets/Images/Quiz_back.png
    - Assets/Images/Quiz_timer.png
    - Assets/Images/Option_A.png
    - Assets/Images/Option_B.png
    - Assets/Images/Option_C.png
    - Assets/Images/Option_D.png
    - Assets/Json/ADBMS.json
    - Assets/Images/test_pg2_adbms1.png
    - Assets/Images/test_pg2_adbms2.png
    - Assets/Images/test_pg2_adbms3.png
    - Assets/Images/test_pg2_adbms4.png

  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Fonts/Poppins/Poppins-Regular.ttf
        - asset: Assets/Fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: Assets/Fonts/Poppins/Poppins-Italic.ttf
          style: italic
